import { saveAs } from 'file-saver';
import type { StructuredStory } from '../store/useLayrStore';

// Lazy load heavy libraries
const loadHtml2Canvas = async () => (await import('html2canvas')).default;
const loadJsPDF = async () => (await import('jspdf')).jsPDF;

export const exportService = {
    async exportStoryAsMarkdown(story: StructuredStory, title: string) {
        if (!story) throw new Error("No story to export");

        const content = `
# ${story.productName || title} - Product Definition

## Description
${story.description}

## Target Users
${(story.targetUsers || []).map(p => `- ${p}`).join('\n')}

## User Roles
${(story.userRoles || []).map(g => `- ${g}`).join('\n')}

## Key Features
${(story.keyFeatures || []).map(f => `- ${f}`).join('\n')}

## Primary User Actions
${(story.primaryUserActions || []).map(a => `- ${a}`).join('\n')}

## System Modules
${(story.systemModules || []).map(m => `- ${m}`).join('\n')}

---
Generated by Layr
`.trim();

        const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
        saveAs(blob, `${title.replace(/\s+/g, '_')}_Story.md`);
    },

    async exportStoryAsPDF(story: StructuredStory, title: string) {
        if (!story) throw new Error("No story to export");

        const jsPDF = await loadJsPDF();
        const doc = new jsPDF();

        // Title
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text(title, 20, 20);
        doc.setFontSize(14);
        doc.setTextColor(100, 100, 100);
        doc.text("Product Definition", 20, 30);

        let y = 50;
        const lineHeight = 10;

        const addSection = (heading: string, items: string[]) => {
            if (y > 270) { doc.addPage(); y = 20; }

            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text(heading, 20, y);
            y += lineHeight;

            doc.setFontSize(12);
            doc.setTextColor(60, 60, 60);

            items.forEach(item => {
                if (y > 280) { doc.addPage(); y = 20; }
                const splitText = doc.splitTextToSize(`• ${item}`, 170);
                doc.text(splitText, 20, y);
                y += (lineHeight * splitText.length);
            });
            y += 5; // Spacing
        };

        // Description
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Description", 20, y);
        y += 8;
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);
        const descLines = doc.splitTextToSize(story.description || '', 170);
        doc.text(descLines, 20, y);
        y += (descLines.length * 8) + 10;

        addSection("Target Users", story.targetUsers || []);
        addSection("User Roles", story.userRoles || []);
        addSection("Key Features", story.keyFeatures || []);
        addSection("Primary User Actions", story.primaryUserActions || []);
        addSection("System Modules", story.systemModules || []);

        doc.save(`${title.replace(/\s+/g, '_')}_Story.pdf`);
    },

    async captureElement(elementId: string): Promise<string> {
        const element = document.getElementById(elementId);
        if (!element) throw new Error(`Element #${elementId} not found`);

        const html2canvas = await loadHtml2Canvas();

        // Improve canvas capture options
        const canvas = await html2canvas(element, {
            backgroundColor: '#09090b', // Match dark theme usually
            scale: 2, // High res
            logging: false,
            useCORS: true,
            ignoreElements: (node) => node.classList.contains('react-flow__controls') || node.classList.contains('do-not-capture')
        });

        return canvas.toDataURL('image/png');
    },

    async exportElementAsImage(elementId: string, filename: string) {
        const dataUrl = await this.captureElement(elementId);
        saveAs(dataUrl, `${filename}.png`);
    },

    async exportFullReport(story: StructuredStory, title: string, iaElementId: string | null, userflowElementId: string | null) {
        const jsPDF = await loadJsPDF();
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        // Page 1: Story
        doc.setFontSize(24);
        doc.text(title, 20, 20);
        doc.setFontSize(16);
        doc.text("Project Report & Specifications", 20, 35);

        doc.setFontSize(12);
        const desc = doc.splitTextToSize(story.description || '', 170);
        doc.text(desc, 20, 50);

        // ... Add detailed lists briefly? 
        // For 'Full Report' maybe just key stats on P1 or just Story full on P1.
        // Let's assume P1 is story summary.

        // Page 2: IA
        if (iaElementId) {
            try {
                const iaImg = await this.captureElement(iaElementId);
                doc.addPage();
                doc.setFontSize(16);
                doc.text("Information Architecture", 20, 20);

                // Fit image
                const imgProps = doc.getImageProperties(iaImg);
                const ratio = imgProps.width / imgProps.height;
                const width = pageWidth - 40;
                const height = width / ratio;

                doc.addImage(iaImg, 'PNG', 20, 30, width, Math.min(height, pageHeight - 50));
            } catch (e) {
                console.warn("Could not capture IA", e);
            }
        }

        // Page 3: Userflow
        if (userflowElementId) {
            try {
                const ufImg = await this.captureElement(userflowElementId);
                doc.addPage();
                doc.setFontSize(16);
                doc.text("User Flow Diagrams", 20, 20);

                // Fit image
                const imgProps = doc.getImageProperties(ufImg);
                const ratio = imgProps.width / imgProps.height;
                const width = pageWidth - 40;
                const height = width / ratio;

                doc.addImage(ufImg, 'PNG', 20, 30, width, Math.min(height, pageHeight - 50));
            } catch (e) {
                console.warn("Could not capture Userflow", e);
            }
        }

        doc.save(`${title.replace(/\s+/g, '_')}_Report.pdf`);
    }
};
